version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: web:p13
    container_name: p13_container
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn p13.wsgi:application --bind 0.0.0.0:$PORT